/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pro;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class altas_nuevo extends javax.swing.JFrame {
 private Connection conexion;
    private Statement st;
    private ResultSet rs;
    
    public void Conectar() {
       try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost:3307/miss", "root", "");
            st = conexion.createStatement();
            rs = st.executeQuery("Select * from altas_nuevo;");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 000" + ex.getMessage());
        }}
    
    
    /**
     * Creates new form altas_nuevo
     */
    public altas_nuevo() {
            initComponents();
            
            Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfid = new javax.swing.JTextField();
        jtfdescripcion = new javax.swing.JTextField();
        jtfprecio_compra = new javax.swing.JTextField();
        jtfprecio_venta = new javax.swing.JTextField();
        jtfexistencias = new javax.swing.JTextField();
        jtfcaducidad = new javax.swing.JTextField();
        jbagregar = new javax.swing.JButton();
        jbborrar = new javax.swing.JButton();
        jbnuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jLabel2.setText("descripcion");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jLabel3.setText("precio compra");

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jLabel4.setText("precio venta");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jLabel5.setText("existencias");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jLabel6.setText("caducidad");

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jLabel1.setText("Id");

        jbagregar.setBackground(new java.awt.Color(255, 153, 0));
        jbagregar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jbagregar.setForeground(new java.awt.Color(0, 102, 255));
        jbagregar.setText("agregar");
        jbagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbagregarMouseClicked(evt);
            }
        });

        jbborrar.setBackground(new java.awt.Color(255, 153, 0));
        jbborrar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jbborrar.setForeground(new java.awt.Color(0, 102, 255));
        jbborrar.setText("borrar");
        jbborrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbborrarMouseClicked(evt);
            }
        });

        jbnuevo.setBackground(new java.awt.Color(255, 153, 0));
        jbnuevo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jbnuevo.setForeground(new java.awt.Color(0, 102, 255));
        jbnuevo.setText("nuevo ");
        jbnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbnuevoMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 36)); // NOI18N
        jLabel7.setText("Ingresos");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro/min.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(173, 173, 173)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbsalir.setBackground(new java.awt.Color(255, 153, 0));
        jbsalir.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jbsalir.setForeground(new java.awt.Color(0, 102, 255));
        jbsalir.setText("salir");
        jbsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbsalirMouseClicked(evt);
            }
        });
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfid, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jtfdescripcion)
                            .addComponent(jtfprecio_compra)
                            .addComponent(jtfprecio_venta)
                            .addComponent(jtfexistencias, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfcaducidad))
                        .addGap(392, 392, 392)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbnuevo)
                .addGap(28, 28, 28)
                .addComponent(jbagregar)
                .addGap(28, 28, 28)
                .addComponent(jbborrar)
                .addGap(42, 42, 42)
                .addComponent(jbsalir)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jtfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jtfdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfprecio_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfprecio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfexistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfcaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbborrar)
                    .addComponent(jbagregar)
                    .addComponent(jbnuevo)
                    .addComponent(jbsalir))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbnuevoMouseClicked
       jtfid.setText("");
       jtfid.setEditable(true);
       jtfdescripcion.setText("");
       jtfdescripcion.setEditable(true);
       jtfprecio_compra.setText("");
       jtfprecio_compra.setEditable(true);
       jtfprecio_venta.setText("");
       jtfprecio_venta.setEditable(true);
       jtfexistencias.setText("");
       jtfexistencias.setEditable(true);
       jtfcaducidad.setText("");
       jtfcaducidad.setEditable(true);
    }//GEN-LAST:event_jbnuevoMouseClicked

    private void jbagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbagregarMouseClicked
        try
       {
            String id=this.jtfid.getText(); 
            String descripcion=this.jtfdescripcion.getText(); 
            String prec=this.jtfprecio_compra.getText(); 
            String precio=this.jtfprecio_venta.getText(); 
            String existencia=this.jtfexistencias.getText(); 
            String caducidad=this.jtfcaducidad.getText(); 
          st.executeUpdate("insert into altas_nuevo (id,descripcion,precio_compra,precio_venta,existencias,caducidad)"
          + " values ('"+id+"','"+descripcion+"','"+prec+"','"+precio+"','"+existencia+"','"+caducidad+"');");
          rs=st.executeQuery("Select * from altas_nuevo");
          rs.next();
          this.jtfid.setText(rs.getString("id"));
          this.jtfdescripcion.setText(rs.getString("descripcion"));
          this.jtfprecio_compra.setText(rs.getString("precio_compra"));
          this.jtfprecio_venta.setText(rs.getString("precio_venta"));
          this.jtfexistencias.setText(rs.getString("existencias"));
          this.jtfcaducidad.setText(rs.getString("caducidad"));
          JOptionPane.showMessageDialog(this,"se agrego el producto" );
          
       }
       catch(SQLException err)
       {
           JOptionPane.showMessageDialog(null,"Error004 "+err.getMessage());
       }
        
        
       
    }//GEN-LAST:event_jbagregarMouseClicked

    private void jbborrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbborrarMouseClicked
       String id=jtfid.getText();
        try{ 
           st.executeUpdate("delete from altas_nuevo where id='"+id+"';");
           JOptionPane.showMessageDialog(null,"Se borro el producto");
           Conectar();

       } catch(SQLException err){ 
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage()); 
        }
    }//GEN-LAST:event_jbborrarMouseClicked

    private void jbsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbsalirMouseClicked
        menu jfmenus=new menu();
        jfmenus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbsalirMouseClicked

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(altas_nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(altas_nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(altas_nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altas_nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new altas_nuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbagregar;
    private javax.swing.JButton jbborrar;
    private javax.swing.JButton jbnuevo;
    private javax.swing.JButton jbsalir;
    private javax.swing.JTextField jtfcaducidad;
    private javax.swing.JTextField jtfdescripcion;
    private javax.swing.JTextField jtfexistencias;
    private javax.swing.JTextField jtfid;
    private javax.swing.JTextField jtfprecio_compra;
    private javax.swing.JTextField jtfprecio_venta;
    // End of variables declaration//GEN-END:variables
}
