/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pro;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class proveedores extends javax.swing.JFrame {
 private Connection conexion;
    private Statement st;
    private ResultSet rs;
     
    public void Conectar() {
       try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost:3307/miss", "root", "");
            st = conexion.createStatement();
            rs = st.executeQuery("Select * from proveedores;");
            moverPrimerRegistro();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 000" + ex.getMessage());
        }
    }
    public void moverPrimerRegistro() {
        try {
            rs.first();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }
     public void moverRegistroSiguiente() {
        try {
            if (!rs.isLast()) {
                rs.next();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }
     public void moverRegistroAnterior() {
        try {
            if (!rs.isFirst()) {
                rs.previous();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }
    
    public void moverUltimoRegistro() {
        try {
            rs.last();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }

    public void llenarDatos() {
        try {
            this.jtfid.setText(rs.getString("id_proveedor"));
            this.jtfempresa.setText(rs.getString("empresa"));
             this.jtffecha.setText(rs.getString("fecha"));
            this.jtfproducto.setText(rs.getString("nombre_producto"));
            this.jtfcantidad_paquetes.setText(rs.getString("cantidad_paquete"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 002" + ex.getMessage());
        }
    }
    public proveedores() {
        initComponents();
        
        Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbagregar = new javax.swing.JButton();
        jbborrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfid = new javax.swing.JTextField();
        jtfempresa = new javax.swing.JTextField();
        jtfproducto = new javax.swing.JTextField();
        jtfcantidad_paquetes = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbprimero = new javax.swing.JButton();
        jbanterior = new javax.swing.JButton();
        jbsiguiente = new javax.swing.JButton();
        jbultimo = new javax.swing.JButton();
        jbnuevo = new javax.swing.JButton();
        jtffecha = new javax.swing.JTextField();
        jbsalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbagregar.setBackground(new java.awt.Color(255, 153, 0));
        jbagregar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jbagregar.setForeground(new java.awt.Color(0, 51, 255));
        jbagregar.setText("agregar");
        jbagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbagregarMouseClicked(evt);
            }
        });

        jbborrar.setBackground(new java.awt.Color(255, 153, 0));
        jbborrar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jbborrar.setForeground(new java.awt.Color(0, 51, 255));
        jbborrar.setText("borrar");
        jbborrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbborrarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jLabel1.setText("id");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jLabel2.setText("empresa");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jLabel3.setText("producto");

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jLabel4.setText("cantidad de paquetes");

        jtfempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfempresaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel5.setBackground(new java.awt.Color(0, 255, 255));
        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 36)); // NOI18N
        jLabel5.setText("Proveedor");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro/min.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(134, 134, 134)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(38, 38, 38))
        );

        jbprimero.setBackground(new java.awt.Color(255, 153, 0));
        jbprimero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbprimero.setText("<<");
        jbprimero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbprimeroMouseClicked(evt);
            }
        });
        jbprimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbprimeroActionPerformed(evt);
            }
        });

        jbanterior.setBackground(new java.awt.Color(255, 153, 0));
        jbanterior.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbanterior.setText("|<");
        jbanterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbanteriorMouseClicked(evt);
            }
        });

        jbsiguiente.setBackground(new java.awt.Color(255, 153, 0));
        jbsiguiente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbsiguiente.setText(">|");
        jbsiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbsiguienteMouseClicked(evt);
            }
        });
        jbsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsiguienteActionPerformed(evt);
            }
        });

        jbultimo.setBackground(new java.awt.Color(255, 153, 0));
        jbultimo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbultimo.setText(">>");
        jbultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbultimoMouseClicked(evt);
            }
        });

        jbnuevo.setBackground(new java.awt.Color(255, 153, 0));
        jbnuevo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jbnuevo.setForeground(new java.awt.Color(0, 51, 255));
        jbnuevo.setText("nuevo");
        jbnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbnuevoMouseClicked(evt);
            }
        });

        jtffecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtffechaActionPerformed(evt);
            }
        });

        jbsalir.setBackground(new java.awt.Color(255, 153, 0));
        jbsalir.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jbsalir.setForeground(new java.awt.Color(0, 51, 255));
        jbsalir.setText("salir");
        jbsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbsalirMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jLabel7.setText("fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfcantidad_paquetes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(jtfempresa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfproducto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfid, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtffecha)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(jbprimero)
                                            .addGap(108, 108, 108)
                                            .addComponent(jbanterior))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(354, 354, 354)
                                            .addComponent(jbsiguiente)
                                            .addGap(65, 65, 65)
                                            .addComponent(jbultimo)))
                                    .addGap(80, 80, 80))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jbnuevo)
                                    .addGap(57, 57, 57)
                                    .addComponent(jbagregar)
                                    .addGap(51, 51, 51)
                                    .addComponent(jbborrar)
                                    .addGap(97, 97, 97)
                                    .addComponent(jbsalir))))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jtfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfcantidad_paquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtffecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jtfempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnuevo)
                    .addComponent(jbagregar)
                    .addComponent(jbborrar)
                    .addComponent(jbsalir))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbanterior)
                    .addComponent(jbprimero)
                    .addComponent(jbsiguiente)
                    .addComponent(jbultimo))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfempresaActionPerformed

    private void jbsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbsiguienteActionPerformed

    private void jbprimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbprimeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbprimeroActionPerformed

    private void jbprimeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbprimeroMouseClicked
        moverPrimerRegistro();
    }//GEN-LAST:event_jbprimeroMouseClicked

    private void jbanteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbanteriorMouseClicked
        moverRegistroAnterior();
    }//GEN-LAST:event_jbanteriorMouseClicked

    private void jbsiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbsiguienteMouseClicked
         moverRegistroSiguiente();
    }//GEN-LAST:event_jbsiguienteMouseClicked

    private void jbultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbultimoMouseClicked
        moverUltimoRegistro();
    }//GEN-LAST:event_jbultimoMouseClicked

    private void jbnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbnuevoMouseClicked
       jtfid.setText("");
       jtfid.setEditable(true);
       jtfempresa.setText("");
       jtfempresa.setEditable(true);
       jtfproducto.setText("");
       jtfproducto.setEditable(true);
       jtfcantidad_paquetes.setText("");
       jtfcantidad_paquetes.setEditable(true);
       jtffecha.setText("");
       jtffecha.setEditable(true);
       
    }//GEN-LAST:event_jbnuevoMouseClicked

    private void jbagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbagregarMouseClicked
        try
       {
            String id=this.jtfid.getText(); 
            String empresa=this.jtfempresa.getText(); 
            String producto=this.jtfproducto.getText(); 
            String cantidad_paquetes=this.jtfcantidad_paquetes.getText(); 
            String fecha=this.jtffecha.getText(); 
          st.executeUpdate("insert into proveedores (id_proveedor,empresa,fecha,nombre_producto,cantidad_paquete)"
          + " values ('"+id+"','"+empresa+"','"+fecha+"','"+producto+"','"+cantidad_paquetes+"');");
          rs=st.executeQuery("Select * from proveedores");
          rs.next();
          this.jtfid.setText(rs.getString("id_proveedor"));
          this.jtfempresa.setText(rs.getString("empresa"));
          this.jtfproducto.setText(rs.getString("nombre_producto"));
          this.jtfcantidad_paquetes.setText(rs.getString("cantidad_paquete"));
          this.jtffecha.setText(rs.getString("fecha"));
          JOptionPane.showMessageDialog(this,"suministro agregado" );
          
          
       }
       catch(SQLException err)
       {
           JOptionPane.showMessageDialog(null,"Error004 "+err.getMessage());
       }    
    }//GEN-LAST:event_jbagregarMouseClicked

    private void jbsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbsalirMouseClicked
        menu jfmenus=new menu();
        jfmenus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbsalirMouseClicked

    private void jbborrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbborrarMouseClicked
    try
      {
        st.executeUpdate("delete from proveedores where id_proveedor="+this.jtfid.getText());
        rs=st.executeQuery("Select * from proveedores");
        rs.next();
        this.jtfid.setText(rs.getString("id_proveedor"));
        this.jtfempresa.setText(rs.getString("empresa"));
        this.jtfproducto.setText(rs.getString("nombre_producto"));
        this.jtfcantidad_paquetes.setText(rs.getString("cantidad_paquete"));
        this.jtffecha.setText(rs.getString("fecha"));
        JOptionPane.showMessageDialog(this,"se borro  correctamente" );
      }
      catch(SQLException err)
      {
        JOptionPane.showMessageDialog(null,"Error005 "+err.getMessage());
      }
                       
    }//GEN-LAST:event_jbborrarMouseClicked

    private void jtffechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtffechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtffechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbagregar;
    private javax.swing.JButton jbanterior;
    private javax.swing.JButton jbborrar;
    private javax.swing.JButton jbnuevo;
    private javax.swing.JButton jbprimero;
    private javax.swing.JButton jbsalir;
    private javax.swing.JButton jbsiguiente;
    private javax.swing.JButton jbultimo;
    private javax.swing.JTextField jtfcantidad_paquetes;
    private javax.swing.JTextField jtfempresa;
    private javax.swing.JTextField jtffecha;
    private javax.swing.JTextField jtfid;
    private javax.swing.JTextField jtfproducto;
    // End of variables declaration//GEN-END:variables
}
