/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pro;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class ventas extends javax.swing.JFrame {
 private Connection conexion;
    private Statement st;
    private ResultSet rs;
    
    public void Conectar() {
       try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost:3307/miss", "root", "");
            st = conexion.createStatement();
            rs = st.executeQuery("Select * from ventas;");
            moverPrimerRegistro();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 000" + ex.getMessage());
        }
    }
    
    public void moverPrimerRegistro() {
        try {
            rs.first();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }
     public void moverRegistroSiguiente() {
        try {
            if (!rs.isLast()) {
                rs.next();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }
     public void moverRegistroAnterior() {
        try {
            if (!rs.isFirst()) {
                rs.previous();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }
    
    public void moverUltimoRegistro() {
        try {
            rs.last();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }

    public void llenarDatos() {
        try {
            this.jtfid_venta.setText(rs.getString("id_venta"));
            this.jtfdescripcion.setText(rs.getString("descripcion"));
            this.jtfprecio.setText(rs.getString("precio"));
            this.jtfcantidad.setText(rs.getString("total"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 002" + ex.getMessage());
        }
    }
    public ventas() {
            initComponents();
            this.setLocationRelativeTo(null);
            Conectar();
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlid_producto = new javax.swing.JLabel();
        jldescripcion = new javax.swing.JLabel();
        jlprecio = new javax.swing.JLabel();
        jltotal = new javax.swing.JLabel();
        jlcantidad = new javax.swing.JLabel();
        jtfid_venta = new javax.swing.JTextField();
        jtfdescripcion = new javax.swing.JTextField();
        jtfprecio = new javax.swing.JTextField();
        jtfcantidad = new javax.swing.JTextField();
        jtftotal = new javax.swing.JTextField();
        jbcobrar = new javax.swing.JButton();
        jblimpiar = new javax.swing.JButton();
        jbprimero = new javax.swing.JButton();
        jbanterior = new javax.swing.JButton();
        jbsiguiente = new javax.swing.JButton();
        jbultimo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbsalir = new javax.swing.JButton();
        jbguardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ventas");

        jlid_producto.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jlid_producto.setText("numero de venta");

        jldescripcion.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jldescripcion.setText("descripcion");

        jlprecio.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jlprecio.setText("precio");

        jltotal.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jltotal.setText("total");

        jlcantidad.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jlcantidad.setText("cantidad");

        jtfid_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfid_ventaActionPerformed(evt);
            }
        });

        jbcobrar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jbcobrar.setForeground(new java.awt.Color(0, 102, 255));
        jbcobrar.setText("cobrar");
        jbcobrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbcobrarMouseClicked(evt);
            }
        });

        jblimpiar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jblimpiar.setForeground(new java.awt.Color(0, 102, 255));
        jblimpiar.setText("limpiar");
        jblimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblimpiarMouseClicked(evt);
            }
        });

        jbprimero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbprimero.setText("<<");
        jbprimero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbprimeroMouseClicked(evt);
            }
        });

        jbanterior.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbanterior.setText("|<");
        jbanterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbanteriorMouseClicked(evt);
            }
        });

        jbsiguiente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbsiguiente.setText(">|");
        jbsiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbsiguienteMouseClicked(evt);
            }
        });
        jbsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsiguienteActionPerformed(evt);
            }
        });

        jbultimo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbultimo.setText(">>");
        jbultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbultimoMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 36)); // NOI18N
        jLabel7.setText("Ventas");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro/min.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(152, 152, 152)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbsalir.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jbsalir.setForeground(new java.awt.Color(51, 102, 255));
        jbsalir.setText("salir");
        jbsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbsalirMouseClicked(evt);
            }
        });

        jbguardar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 24)); // NOI18N
        jbguardar.setForeground(new java.awt.Color(0, 102, 255));
        jbguardar.setText("guardar");
        jbguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbguardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbsalir)
                                .addGap(38, 38, 38)
                                .addComponent(jbcobrar)
                                .addGap(47, 47, 47)
                                .addComponent(jbguardar)
                                .addGap(70, 70, 70)
                                .addComponent(jblimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jbprimero)
                                .addGap(88, 88, 88)
                                .addComponent(jbanterior)
                                .addGap(69, 69, 69)
                                .addComponent(jbsiguiente)
                                .addGap(61, 61, 61)
                                .addComponent(jbultimo)))
                        .addGap(59, 125, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(67, 67, 67)
                                            .addComponent(jldescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jlid_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(jltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfdescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(jtfid_venta)
                            .addComponent(jtfprecio)
                            .addComponent(jtfcantidad)
                            .addComponent(jtftotal))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlid_producto)
                    .addComponent(jtfid_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jldescripcion)
                    .addComponent(jtfdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlcantidad)
                    .addComponent(jtfcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jltotal)
                    .addComponent(jtftotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbsalir)
                    .addComponent(jbcobrar)
                    .addComponent(jbguardar)
                    .addComponent(jblimpiar))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbprimero)
                    .addComponent(jbanterior)
                    .addComponent(jbsiguiente)
                    .addComponent(jbultimo))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbsiguienteActionPerformed

    private void jbprimeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbprimeroMouseClicked
          
          moverPrimerRegistro();
    }//GEN-LAST:event_jbprimeroMouseClicked

    private void jtfid_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfid_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfid_ventaActionPerformed

    private void jbanteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbanteriorMouseClicked
        moverRegistroAnterior();
    }//GEN-LAST:event_jbanteriorMouseClicked

    private void jbsiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbsiguienteMouseClicked
       moverRegistroSiguiente();
    }//GEN-LAST:event_jbsiguienteMouseClicked

    private void jbultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbultimoMouseClicked
        moverUltimoRegistro();
    }//GEN-LAST:event_jbultimoMouseClicked

    private void jbsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbsalirMouseClicked
        menu jfmenus=new menu();
        jfmenus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbsalirMouseClicked

    private void jbcobrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbcobrarMouseClicked
        float numero1 = 0.0f;
        float numero2 = 0.0f;
        float resultado = 0.0f;
        
        numero1= Float.parseFloat(this.jtfprecio.getText());
        
        numero2= Float.parseFloat(this.jtfcantidad.getText());
        
        resultado = numero1 * numero2;
        
        this.jtftotal.setText(String.valueOf(resultado));
    }//GEN-LAST:event_jbcobrarMouseClicked

    private void jblimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblimpiarMouseClicked
        jtfid_venta.setText("");
       jtfid_venta.setEditable(true);
       jtfdescripcion.setText("");
       jtfdescripcion.setEditable(true);
       jtfprecio.setText("");
       jtfprecio.setEditable(true);
       jtfcantidad.setText("");
       jtfcantidad.setEditable(true);
       jtftotal.setText("");
       jtftotal.setEditable(true);
    }//GEN-LAST:event_jblimpiarMouseClicked

    private void jbguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbguardarMouseClicked
         try
       {
        String id=this.jtfid_venta.getText(); 
        String descripcion=this.jtfdescripcion.getText(); 
        String precio=this.jtfprecio.getText(); 
        String cantidad=this.jtfcantidad.getText(); 
        String total=this.jtftotal.getText(); 
          st.executeUpdate("insert into ventas (id_venta,descripcion,precio,cantidad,total)"
          + " values ('"+id+"','"+descripcion+"','"+precio+"','"+cantidad+"','"+total+"');");
          rs=st.executeQuery("Select * from ventas");
          rs.next();
          this.jtfid_venta.setText(rs.getString("id_venta"));
          this.jtfdescripcion.setText(rs.getString("descripcion"));
          this.jtfprecio.setText(rs.getString("precio"));
          this.jtfcantidad.setText(rs.getString("cantidad"));
          this.jtftotal.setText(rs.getString("total"));
          JOptionPane.showMessageDialog(this,"se guardo tu venta" );
          
          
       }
       catch(SQLException err)
       {
           JOptionPane.showMessageDialog(null,"Error004 "+err.getMessage());
       }    
    }//GEN-LAST:event_jbguardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbanterior;
    private javax.swing.JButton jbcobrar;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jblimpiar;
    private javax.swing.JButton jbprimero;
    private javax.swing.JButton jbsalir;
    private javax.swing.JButton jbsiguiente;
    private javax.swing.JButton jbultimo;
    private javax.swing.JLabel jlcantidad;
    private javax.swing.JLabel jldescripcion;
    private javax.swing.JLabel jlid_producto;
    private javax.swing.JLabel jlprecio;
    private javax.swing.JLabel jltotal;
    private javax.swing.JTextField jtfcantidad;
    private javax.swing.JTextField jtfdescripcion;
    private javax.swing.JTextField jtfid_venta;
    private javax.swing.JTextField jtfprecio;
    private javax.swing.JTextField jtftotal;
    // End of variables declaration//GEN-END:variables
}
